name: PR Reminder

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  slack-bot-token:
    description: 'Slack bot token'
    required: true
  slack-channel-id:
    description: 'Slack channel ID'
    required: true
  owner-name:
    description: 'Repository owner'
    required: true
  repo-name:
    description: 'Repository name'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: install packages
      shell: bash
      run: npm install
      working-directory: '${{ github.action_path }}'
    - name: pr-reminder
      shell: bash
      run: node src/pr-reminder.js
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_CHANNEL_ID: ${{ inputs.slack-channel-id }}
        OWNER_NAME: ${{ inputs.owner-name }}
        REPO_NAME: ${{ inputs.repo-name }}
